version: "3.9"

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:oracle@sha256:e1866c1d0f58b69de7fa0b5986564ae044784f0dd1c61c01bbf3ec1470784312
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - 3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      sql-playground:
        ipv4_address: 129.0.0.3

  postgres-db:
    container_name: postgres-db
    image: postgres:12.10@sha256:d3ccc43754fd0bf96409ad68286a1f32d4391ab25f4384b4a4e1376e0d2c70cf
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    networks:
      sql-playground:
        ipv4_address: 129.0.0.4

networks:
  sql-playground:
    ipam:
      driver: default
      config:
        - subnet: "129.0.0.0/24"
